#[derive(Clone, Copy)]
pub enum AuditAction {
  AuthLogin,
  AuthLogout,
  AuthChangePassword,
  AuthResetPassword,
  OperatorList,
  OperatorCreate,
  OperatorUpdate,
  OperatorStatus,
  WarehouseList,
  WarehouseCreate,
  WarehouseUpdate,
  WarehouseStatus,
  RackList,
  RackCreate,
  RackUpdate,
  RackStatus,
  SlotList,
  SlotRegen,
  SlotStatus,
  ItemList,
  ItemCreate,
  ItemUpdate,
  ItemStatus,
  MediaAttachmentItemAdd,
  MediaAttachmentItemList,
  MediaAttachmentItemRemove,
  MediaAttachmentItemReorder,
  MediaAttachmentItemPathRewrite,
  MediaAttachmentTxnAdd,
  MediaAttachmentTxnList,
  MediaAttachmentTxnRemove,
  MediaAttachmentTxnPathRewrite,
  TxnInbound,
  TxnOutbound,
  TxnMove,
  TxnCount,
  TxnReversal,
  TxnList,
  SystemSettingsUpdate,
  SystemSettingsRead,
  SystemStorageRootChange,
  AuditList,
  AuditExport,
  StockListBySlot,
  StockListByItem,
  StockExport,
  DbBackup,
  DbRestore,
  ItemExport,
  ItemImport,
  TxnExport,
  TxnImport,
  DashboardOverview,
}

impl AuditAction {
  // 审计动作字符串必须与规范一致
  pub fn as_str(&self) -> &'static str {
    match self {
      AuditAction::AuthLogin => "AUTH_LOGIN",
      AuditAction::AuthLogout => "AUTH_LOGOUT",
      AuditAction::AuthChangePassword => "AUTH_CHANGE_PASSWORD",
      AuditAction::AuthResetPassword => "AUTH_RESET_PASSWORD",
      AuditAction::OperatorList => "OPERATOR_LIST",
      AuditAction::OperatorCreate => "OPERATOR_CREATE",
      AuditAction::OperatorUpdate => "OPERATOR_UPDATE",
      AuditAction::OperatorStatus => "OPERATOR_STATUS",
      AuditAction::WarehouseList => "WAREHOUSE_LIST",
      AuditAction::WarehouseCreate => "WAREHOUSE_CREATE",
      AuditAction::WarehouseUpdate => "WAREHOUSE_UPDATE",
      AuditAction::WarehouseStatus => "WAREHOUSE_STATUS",
      AuditAction::RackList => "RACK_LIST",
      AuditAction::RackCreate => "RACK_CREATE",
      AuditAction::RackUpdate => "RACK_UPDATE",
      AuditAction::RackStatus => "RACK_STATUS",
      AuditAction::SlotList => "SLOT_LIST",
      AuditAction::SlotRegen => "SLOT_REGEN",
      AuditAction::SlotStatus => "SLOT_STATUS",
      AuditAction::ItemList => "ITEM_LIST",
      AuditAction::ItemCreate => "ITEM_CREATE",
      AuditAction::ItemUpdate => "ITEM_UPDATE",
      AuditAction::ItemStatus => "ITEM_STATUS",
      AuditAction::MediaAttachmentItemAdd => "MEDIA_ATTACHMENT_ITEM_ADD",
      AuditAction::MediaAttachmentItemList => "MEDIA_ATTACHMENT_ITEM_LIST",
      AuditAction::MediaAttachmentItemRemove => "MEDIA_ATTACHMENT_ITEM_REMOVE",
      AuditAction::MediaAttachmentItemReorder => "MEDIA_ATTACHMENT_ITEM_REORDER",
      AuditAction::MediaAttachmentItemPathRewrite => "MEDIA_ATTACHMENT_ITEM_PATH_REWRITE",
      AuditAction::MediaAttachmentTxnAdd => "MEDIA_ATTACHMENT_TXN_ADD",
      AuditAction::MediaAttachmentTxnList => "MEDIA_ATTACHMENT_TXN_LIST",
      AuditAction::MediaAttachmentTxnRemove => "MEDIA_ATTACHMENT_TXN_REMOVE",
      AuditAction::MediaAttachmentTxnPathRewrite => "MEDIA_ATTACHMENT_TXN_PATH_REWRITE",
      AuditAction::TxnInbound => "TXN_INBOUND",
      AuditAction::TxnOutbound => "TXN_OUTBOUND",
      AuditAction::TxnMove => "TXN_MOVE",
      AuditAction::TxnCount => "TXN_COUNT",
      AuditAction::TxnReversal => "TXN_REVERSAL",
      AuditAction::TxnList => "TXN_LIST",
      AuditAction::SystemSettingsUpdate => "SYSTEM_SETTINGS_UPDATE",
      AuditAction::SystemSettingsRead => "SYSTEM_SETTINGS_READ",
      AuditAction::SystemStorageRootChange => "SYSTEM_STORAGE_ROOT_CHANGE",
      AuditAction::AuditList => "AUDIT_LIST",
      AuditAction::AuditExport => "AUDIT_EXPORT",
      AuditAction::StockListBySlot => "STOCK_LIST_BY_SLOT",
      AuditAction::StockListByItem => "STOCK_LIST_BY_ITEM",
      AuditAction::StockExport => "STOCK_EXPORT",
      AuditAction::DbBackup => "DB_BACKUP",
      AuditAction::DbRestore => "DB_RESTORE",
      AuditAction::ItemExport => "ITEM_EXPORT",
      AuditAction::ItemImport => "ITEM_IMPORT",
      AuditAction::TxnExport => "TXN_EXPORT",
      AuditAction::TxnImport => "TXN_IMPORT",
      AuditAction::DashboardOverview => "DASHBOARD_OVERVIEW",
    }
  }
}
